name: Scala Steward GitHub Action
author: The Scala Steward contributors
description: 🤖 A bot that helps you keeping your Scala projects up-to-date
branding:
  icon: arrow-up-circle
  color: red

inputs:
  artifact-migrations:
    description: |
      Artifact migrations for newer versions of artifacts with
      different group Ids, artifact ids, or both different.

      Expects the path to HOCON file with migration/s.

      See https://github.com/scala-steward-org/scala-steward/blob/main/docs/artifact-migrations.md
    required: false
  author-email:
    description: |
      Author email address to use in commits. If set it will
      override any email retrieved from GitHub.
    required: false
  author-name:
    description: |
      Author name to use in commits. If set it will override
      any name retrieved from GitHub.
    required: false
  branches:
    description: |
      A comma-separated list of branches to update (if not
      provided, the repository's default branch will be
      updated instead).

      This option only has effect if updating the current
      repository or using the `github-repository` input.
    required: false
  cache-ttl:
    description: |
      TTL of cache for fetching dependency versions and
      metadata, set it to 0s to disable it.
    default: 2hours
    required: false
  max-buffer-size:
    description: |
      Size of the buffer for the output of an external process
      in lines. The default is 16384.
    default: "16384"
    required: false
  coursier-cli-url:
    description: |
      Url to download the coursier linux CLI from.
    default: https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz
    required: false
  extra-jars:
    description: |
      Extra JARs to be added to the classpath of the
      launched application. Directories accepted too.
    required: false
  github-api-url:
    description: |
      The URL of the GitHub API, only use this input if
      you are using GitHub Enterprise.
    default: ${{ github.api_url }}
    required: false
  github-app-auth-only:
    description: |
      If set to `true` the GitHub App information will
      only be used for authentication.

      Repositories to update will be read from either
      the `repos-file` or the `github-repository` inputs.
    default: "false"
    required: false
  github-app-id:
    description: |
      GitHub App ID. See the "Installation" section of the
      README to learn how to set up the app and how to fill this input.
    required: false
  github-app-installation-id:
    description: |
      GitHub App Installation ID. See the "Installation"
      section of the README to learn how to set up the app
      and how to fill this input.
    required: false
  github-app-key:
    description: |
      GitHub App Private Key. See the "Installation" section
      of the README to learn how to set up the app and how to
      fill this input.
    required: false
  github-repository:
    description: |
      Repository to update. Will be ignored if either
      `repos-file` is provided or the `github-app-*`
      inputs are and `github-app-auth-only` is not `true`.
    required: false
    default: ${{ github.repository }}
  github-token:
    description: |
      GitHub Personal Access Token with permission to create
      branches on repo.

      If `github-app-*` inputs are provided an App's
      installation token will be used instead of this one.
    required: false
    default: ${{ github.token }}
  ignore-opts-files:
    description: |
      Whether to ignore "opts" files (such as `.jvmopts`
      or `.sbtopts`) when found on repositories or not.
    default: "true"
    required: false
  mill-version:
    description: |
      Mill version to install. Take into account this will
      just affect the global `mill` executable. Scala 
      Steward will still respect the version specified in
      your repository while updating it.
    default: "0.10.9"
    required: false
  other-args:
    description: |
      Other Scala Steward arguments not yet supported by
      this action as a separate argument.
    required: false
  repo-config:
    description: |
      Location of a `.scala-steward.conf` file with default
      values.

      If the provided file is missing the action will fail.
    default: ".github/.scala-steward.conf"
    required: false
  repos-file:
    description: |
      Path to a file containing the list of repositories
      to update in markdown format:

      - owner/repo1
      - owner/repo2

      This input will be ignored if the `github-app-*`
      inputs are provided and `github-app-auth-only` is
      not `true`.
    required: false
  scala-steward-version:
    description: |
      Scala Steward version to use. If not provided it
      will use the last one published.
    required: false
  scalafix-migrations:
    description: |
      Scalafix rules for version updates to run after
      certain updates.

      Expects the path to HOCON file with migration/s.

      See https://github.com/scala-steward-org/scala-steward/blob/main/docs/scalafix-migrations.md
    required: false
  sign-commits:
    description: |
      Whether to sign commits or not.
    default: "false"
    required: false
  signing-key:
    description: |
      Key ID of GPG key to use for signing commits. See the
      "Signing commits with GPG" section to learn how to
      prepare the environment and fill this input.
    default: ""
    required: false
  timeout:
    description: |
      Timeout for external process invocations.
    default: 20min
    required: false

runs:
  using: node20
  pre: dist/pre.js
  main: dist/main.js
  post: dist/post.js
