name: "Scala Steward Github Action"
author: alejandrohdezma
description: "🤖 A bot that helps you keeping your Scala projects up-to-date "
branding:
  icon: arrow-up-circle
  color: red

inputs:
  repos-file:
    description: "Path to a file containing the list of repositories to update in markdown format (- owner/repo)"
    required: false
  github-repository:
    description: "Repository to update. The current repository will be used by default"
    required: false
  github-token:
    description: "Github Personal Access Token with permission to create branches on repo"
    required: false
    default: ${{ github.token }}
  author-email:
    description: Author email address to use in commits
    required: false
  author-name:
    description: Author name to use in commits
    required: false
  scala-steward-version:
    description: "Scala Steward version to use"
    default: "0.12.0"
    required: false
  ignore-opts-files:
    description: 'Whether to ignore "opts" files (such as `.jvmopts` or `.sbtopts`) when found on repositories or not'
    default: "true"
    required: false
  branches:
    description:
      A comma-separated list of branches to update (if not provided, the repository's default branch will be
      updated instead). This option only has effect if updating the current repository or using the `github-repository` input.
    required: false
  sign-commits:
    description: "Whether to sign commits or not"
    default: "false"
    required: false
  timeout:
    description: "Timeout for external process invocations"
    default: "20min"
    required: false
  cache-ttl:
    description: "TTL of cache for fetching dependency versions and metadata, set it to 0s to disable it"
    default: "2hours"
    required: false
  github-api-url:
    description: "The URL of the Github API, only use this input if you are using Github Enterprise"
    default: "https://api.github.com"
    required: false
  scalafix-migrations:
    description: "https://github.com/scala-steward-org/scala-steward/blob/5dafbcd522a0465af7fbbaf4304d48a7b25e3516/docs/scalafix-migrations.md"
    required: false
  artifact-migrations:
    description: "https://github.com/scala-steward-org/scala-steward/blob/5dafbcd522a0465af7fbbaf4304d48a7b25e3516/docs/artifact-migrations.md"
    required: false
  github-app-id:
    description: "Github application ID"
    required: false
  github-app-key:
    description: "Github application private key"
    required: false
  default-repo-conf:
    description: "Location of a `.scala-steward.conf` file with default values"
    default: ".github/.scala-steward.conf"
    required: false

runs:
  using: "node12"
  main: "dist/main.js"
  post: "dist/post.js"
