# Releases a new minor version every time a PR is merged into `master`.
#
# It also generates the `dist` folder inside the tag's commit, keeping
#   the `master` branch clean.
#
# It will also update the major tag v2 to track the latest tag.

name: Release new version

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  new-release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: master

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run build`
        run: npm run build

      - name: Release new version
        uses: int128/release-typescript-action@a0525ac9f7a841d2bd0280d735a0ebbd99eb6d01 # v1.60.0
        with:
          major-version: 2

  update-docs:
    name: Update documentation
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: master
          ssh-key: ${{ secrets.GIT_DEPLOY_KEY }}

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run docs`
        run: npm run docs

      - name: Commit changes by `npm run docs`
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Run `npm run docs` [skip ci]
          branch: master
